name: Auto Update README and Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'   # Weekly update (optional)
  workflow_dispatch:      # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install matplotlib

      - name: Run stat and chart generation scripts
        run: |
          python misc/update_stats.py
          python misc/chart_difficulty.py
          python misc/chart_language.py
          python misc/update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md stats.json assets/chart_*.svg
          git diff --cached --quiet || git commit -m "Auto-update README and charts"
          git push
